<a href="https://colab.research.google.com/github/andressonsino/student-ai-impact-analysis/blob/main/impact_of_ia_on_students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings

# Supresión de warnings
warnings.filterwarnings('ignore')
pd.options.mode.chained_assignment = None

# Configuración de visualización del DataFrame
pd.set_option('display.max_columns', None)   # muestra todas las columnas
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

# Configuración de gráficos
sns.set_theme(style='whitegrid')
sns.set_palette('husl')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['axes.titlesize'] = 16
plt.rcParams['axes.labelsize'] = 13

In [34]:
## ── Configuración ──────────────────────────────────────────
#DATA_PATH = r"data/raw/archivo.csv"  # ← CAMBIAR: ruta al archivo usar ../ al principio si debo ubicarme en una carpeta anterior
#SEPARATOR = ","                  # ← CAMBIAR si es otro separador (";", "\t", etc.)
#ENCODING  = "utf-8"              # ← CAMBIAR si hay problemas de caracteres
## ───────────────────────────────────────────────────────────
#
#df_raw = pd.read_csv(DATA_PATH, sep=SEPARATOR, encoding=ENCODING)
#print(f"✅ Dataset cargado — Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}")

from google.colab import drive

# Montar Google Drive (te va a pedir autorización la primera vez)
drive.mount('/content/drive')

# ── Configuración ──────────────────────────────────────────
DRIVE_PATH = "MyDrive/trabajo/ds/datasets/ifts/ai_student_impact_dataset.csv"
# ───────────────────────────────────────────────────────────

ruta_completa = f"/content/drive/{DRIVE_PATH}"

df_raw = pd.read_csv(ruta_completa)
print(f"✅ Dataset cargado desde Google Drive — Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Dataset cargado desde Google Drive — Filas: 50000 | Columnas: 16

In [35]:
# ─── Primeras y últimas filas ──────────────────────────────────────────────
print('\n--- Primeras 5 filas ---')
display(df_raw.head())

print('\n--- Últimas 5 filas ---')
display(df_raw.tail())

# ─── Dimensiones ───────────────────────────────────────────────────────────
print(f'Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}')

# ─── Tipos de datos ────────────────────────────────────────────────────────
print('\n--- Info general ---')
df_raw.info()

# ─── Valores nulos por columna ─────────────────────────────────────────────
print('\n--- Nulos por columna ---')
# Verificamos si hay algún nulo en toda la tabla
if df_raw.isnull().sum().sum() == 0:
    print('✅ Sin valores nulos')
else:
    # Sino mostramos tabla filtrada de nulos
    nulos = pd.DataFrame({
        'Nulos': df_raw.isnull().sum(),
        'Porcentaje': (df_raw.isnull().sum() / len(df_raw) * 100).round(2)
    })
    display(nulos[nulos['Nulos'] > 0])

# ─── Duplicados ────────────────────────────────────────────────────────────
print(f'\nFilas duplicadas: {df_raw.duplicated().sum()}')

# ─── Estadísticas descriptivas ─────────────────────────────────────────────
print('\n--- Estadísticas descriptivas ---')
display(df_raw.describe())

--- Primeras 5 filas ---

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.42,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.39,86.44,High
1,100002,Medical,Junior,3.82,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.70,69.39,Low
2,100003,Business,Freshman,3.40,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.50,73.93,Medium
3,100004,Business,Senior,3.79,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.00,63.58,Medium
4,100005,STEM,Sophomore,3.63,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.80,100.00,Medium

--- Últimas 5 filas ---

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49995,149996,Business,Senior,2.90,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.58,66.16,High
49996,149997,STEM,Senior,2.87,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.10,81.62,Medium
49997,149998,Business,Senior,3.18,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.60,97.21,High
49998,149999,Business,Junior,3.40,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.53,84.12,Medium
49999,150000,Arts,Sophomore,3.24,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.26,76.16,Low

Filas: 50000 | Columnas: 16

--- Info general ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

--- Nulos por columna ---
✅ Sin valores nulos

Filas duplicadas: 0

--- Estadísticas descriptivas ---

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00
mean,125000.50,3.15,8.43,2.80,11.21,3.51,4.27,3.35,75.80
std,14433.90,0.48,8.27,1.19,5.16,1.82,2.14,0.50,13.28
min,100001.00,1.18,0.00,1.00,1.00,1.00,1.00,1.00,10.78
25%,112500.75,2.83,2.39,2.00,7.56,2.00,3.00,3.02,66.82
50%,125000.50,3.21,5.80,3.00,11.18,3.00,4.00,3.42,76.00
75%,137500.25,3.52,11.72,4.00,14.71,5.00,6.00,3.75,85.19
max,150000.00,4.00,40.00,5.00,35.86,10.00,10.00,4.00,100.00

In [36]:
# 1. Diccionario SOLO para renombrar encabezados de columnas
diccionario_columnas = {
    'Student_ID': 'ID del estudiante',
    'Major_Category': 'Categoría de carrera',
    'Year_of_Study': 'Año de cursada',
    'Pre_Semester_GPA': 'Promedio académico antes del semestre',
    'Weekly_GenAI_Hours': 'Horas semanales de uso de IA generativa',
    'Primary_Use_Case': 'Uso principal de la IA',
    'Prompt_Engineering_Skill': 'Nivel de habilidad en prompt engineering',
    'Tool_Diversity': 'Diversidad de herramientas de IA utilizadas',
    'Paid_Subscription': 'Tiene suscripción paga',
    'Traditional_Study_Hours': 'Horas de estudio tradicional',
    'Perceived_AI_Dependency': 'Dependencia percibida de la IA',
    'Institutional_Policy': 'Política institucional sobre uso de IA',
    'Anxiety_Level_During_Exams': 'Nivel de ansiedad durante exámenes',
    'Post_Semester_GPA': 'Promedio académico después del semestre',
    'Skill_Retention_Score': 'Puntaje de retención de habilidades',
    'Burnout_Risk_Level': 'Nivel de riesgo de burnout'
}

# 2. Diccionario SOLO para traducir el contenido de las celdas (filas)
diccionario_contenido = {
    'Categoría de carrera': {
        'Humanities': 'Humanidades',
        'Medical': 'Medicina',
        'Business': 'Negocios',
        'STEM': 'CTIM (Ciencias, Tecnología, Ing. y Matemáticas)',
        'Arts': 'Artes'
    },
    "Año de cursada" : {
    'Freshman': '1er año',
    'Sophomore': '2do año',
    'Junior': '3er año',
    'Senior': '4to año'
    },
    'Uso principal de la IA': {
        'Copywriting/Drafting': 'Redacción/Borradores',
        'Ideation': 'Ideación',
        'Summarizing_Reading': 'Resumir_Lectura',
        'Debugging/Troubleshooting': 'Depuración/Resolución_de_Problemas'
    },
    'Nivel de habilidad en prompt engineering': {
        'Beginner': 'Principiante',
        'Intermediate': 'Intermedio',
        'Advanced': 'Avanzado'
    },
    'Política institucional sobre uso de IA': {
        'Allowed_With_Citation': 'Permitido con cita',
        'Strict_Ban': 'Prohibición estricta',
        'Actively_Encouraged': 'Fomentado activamente'
    },
    'Nivel de riesgo de burnout': {
        'Low': 'Bajo',
        'Medium': 'Medio',
        'High': 'Alto'
    }
}

# --- EJECUCIÓN DEL CAMBIO ---

# Paso A: Renombrar títulos de columnas
df_raw = df_raw.rename(columns=diccionario_columnas)

# Paso B: Traducir el contenido de las filas
df_raw = df_raw.replace(diccionario_contenido)

# Paso C: Traducir la columna True/False
df_raw['Tiene suscripción paga'] = df_raw['Tiene suscripción paga'].replace({
    True: 'Sí', False: 'No', 'True': 'Sí', 'False': 'No'
})

print("✅ Columnas y filas traducidas correctamente")

✅ Columnas y filas traducidas correctamente

In [37]:
df_raw

,ID del estudiante,Categoría de carrera,Año de cursada,Promedio académico antes del semestre,Horas semanales de uso de IA generativa,Uso principal de la IA,Nivel de habilidad en prompt engineering,Diversidad de herramientas de IA utilizadas,Tiene suscripción paga,Horas de estudio tradicional,Dependencia percibida de la IA,Política institucional sobre uso de IA,Nivel de ansiedad durante exámenes,Promedio académico después del semestre,Puntaje de retención de habilidades,Nivel de riesgo de burnout
0,100001,Humanidades,4to año,2.42,23.31,Redacción/Borradores,Principiante,1,Sí,8.13,5,Permitido con cita,6,2.39,86.44,Alto
1,100002,Medicina,3er año,3.82,1.12,Ideación,Avanzado,5,No,16.65,3,Permitido con cita,9,3.70,69.39,Bajo
2,100003,Negocios,1er año,3.40,21.26,Resumir_Lectura,Principiante,2,No,10.35,5,Prohibición estricta,9,3.50,73.93,Medio
3,100004,Negocios,4to año,3.79,1.82,Redacción/Borradores,Intermedio,4,No,15.23,2,Permitido con cita,2,4.00,63.58,Medio
4,100005,"CTIM (Ciencias, Tecnología, Ing. y Matemáticas)",2do año,3.63,9.29,Depuración/Resolución_de_Problemas,Avanzado,4,No,12.55,4,Permitido con cita,4,3.80,100.00,Medio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Negocios,4to año,2.90,12.16,Redacción/Borradores,Principiante,2,No,13.36,2,Permitido con cita,2,3.58,66.16,Alto
49996,149997,"CTIM (Ciencias, Tecnología, Ing. y Matemáticas)",4to año,2.87,2.51,Redacción/Borradores,Intermedio,1,No,4.67,3,Fomentado activamente,3,3.10,81.62,Medio
49997,149998,Negocios,4to año,3.18,15.87,Resumir_Lectura,Avanzado,5,Sí,3.92,4,Permitido con cita,5,3.60,97.21,Alto
49998,149999,Negocios,3er año,3.40,19.91,Depuración/Resolución_de_Problemas,Intermedio,5,No,7.10,5,Permitido con cita,3,3.53,84.12,Medio
49999,150000,Artes,2do año,3.24,3.30,Redacción/Borradores,Principiante,1,No,3.93,2,Permitido con cita,6,3.26,76.16,Bajo

In [39]:
# ─── Estadísticas descriptivas ─────────────────────────────────────────────
print('\n--- Estadísticas descriptivas ---')
display(df_raw.describe())

--- Estadísticas descriptivas ---

,ID del estudiante,Promedio académico antes del semestre,Horas semanales de uso de IA generativa,Diversidad de herramientas de IA utilizadas,Horas de estudio tradicional,Dependencia percibida de la IA,Nivel de ansiedad durante exámenes,Promedio académico después del semestre,Puntaje de retención de habilidades
count,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00,50000.00
mean,125000.50,3.15,8.43,2.80,11.21,3.51,4.27,3.35,75.80
std,14433.90,0.48,8.27,1.19,5.16,1.82,2.14,0.50,13.28
min,100001.00,1.18,0.00,1.00,1.00,1.00,1.00,1.00,10.78
25%,112500.75,2.83,2.39,2.00,7.56,2.00,3.00,3.02,66.82
50%,125000.50,3.21,5.80,3.00,11.18,3.00,4.00,3.42,76.00
75%,137500.25,3.52,11.72,4.00,14.71,5.00,6.00,3.75,85.19
max,150000.00,4.00,40.00,5.00,35.86,10.00,10.00,4.00,100.00

In [41]:
# Detectar con IQR
def detectar_outliers(df, columna):
    Q1 = df[columna].quantile(0.25)
    Q3 = df[columna].quantile(0.75)
    IQR = Q3 - Q1
    lim_inf = Q1 - 1.5 * IQR
    lim_sup = Q3 + 1.5 * IQR
    outliers = df[(df[columna] < lim_inf) | (df[columna] > lim_sup)]
    print(f'{columna}:')
    print(f'  Rango normal: [{lim_inf:.2f}, {lim_sup:.2f}]')
    print(f'  Outliers: {len(outliers)} ({len(outliers)/len(df)*100:.1f}%)\n')
    return lim_inf, lim_sup

# Bucle for para utilizar esta funcion en cada columna
# Filtramos para agarrar solo las columnas que tienen números (ignoramos textos/nombres)
columnas_numericas = df_raw.select_dtypes(include=['number']).columns

# Hacemos que Python pase la función por cada una de esas columnas automáticamente
for col in columnas_numericas:
    detectar_outliers(df_raw, col)
    print("-" * 40) # Imprime una línea separadora para que se lea mejor

ID del estudiante:
  Rango normal: [75001.50, 174999.50]
  Outliers: 0 (0.0%)

----------------------------------------
Promedio académico antes del semestre:
  Rango normal: [1.80, 4.55]
  Outliers: 328 (0.7%)

----------------------------------------
Horas semanales de uso de IA generativa:
  Rango normal: [-11.61, 25.72]
  Outliers: 2583 (5.2%)

----------------------------------------
Diversidad de herramientas de IA utilizadas:
  Rango normal: [-1.00, 7.00]
  Outliers: 0 (0.0%)

----------------------------------------
Horas de estudio tradicional:
  Rango normal: [-3.17, 25.44]
  Outliers: 161 (0.3%)

----------------------------------------
Dependencia percibida de la IA:
  Rango normal: [-2.50, 9.50]
  Outliers: 190 (0.4%)

----------------------------------------
Nivel de ansiedad durante exámenes:
  Rango normal: [-1.50, 10.50]
  Outliers: 0 (0.0%)

----------------------------------------
Promedio académico después del semestre:
  Rango normal: [1.94, 4.84]
  Outliers: 346 (0.7%)

----------------------------------------
Puntaje de retención de habilidades:
  Rango normal: [39.26, 112.75]
  Outliers: 216 (0.4%)

----------------------------------------